# Generated by Django 5.1.6 on 2025-04-02 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_structure', '0001_initial'),
        ('staffing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filialdepartment',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='staffing.employee', verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='filialdepartment',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_structure.filial', verbose_name='Филиал'),
        ),
        migrations.AlterUniqueTogether(
            name='filialdepartment',
            unique_together={('filial', 'name')},
        ),
    ]
