# Generated by Django 5.1.6 on 2025-03-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_structure', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='uuid',
        ),
        migrations.AlterUniqueTogether(
            name='filialdepartment',
            unique_together={('filial', 'name')},
        ),
        migrations.RemoveField(
            model_name='filialdepartment',
            name='uuid',
        ),
    ]
