openapi: 3.0.0
info:
  title: Example API
  description: Пример API для работы с пользователями
  version: 1.0.0

servers:
  - url: http://localhost:5000/api
    description: Локальный сервер

paths:
  /users:
    get:
      summary: Получить список пользователей
      operationId: getUsers
      tags:
        - Users
      responses:
        "200":
          description: Успешный ответ со списком пользователей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"

  /users/{id}:
    get:
      summary: Получить пользователя по ID
      operationId: getUserById
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Данные пользователя
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: Пользователь не найден

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Иван Иванов"
        email:
          type: string
          format: email
          example: "ivan@example.com"
