# Generated by Django 5.1.6 on 2025-04-02 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('company_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('suffix', models.CharField(blank=True, max_length=16, null=True, verbose_name='Суффикс номера карты')),
                ('prefix', models.CharField(blank=True, max_length=16, null=True, verbose_name='Префикс номера карты')),
                ('begin_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Начальный номер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип мед.карты',
                'verbose_name_plural': 'Типы мед.карты',
            },
        ),
        migrations.CreateModel(
            name='MedicalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_signed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Подписано ЭП')),
                ('signed_date', models.DateField(auto_now=True, null=True, verbose_name='Дата подписания')),
                ('org_signature', models.TextField(blank=True, null=True, verbose_name='Организационная подпись')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('number', models.CharField(max_length=64, verbose_name='Номер карты')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('date_closed', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_cards', to='clients.patient', verbose_name='Пациент')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_structure.filial', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Медицинская карта',
                'verbose_name_plural': 'Медицинские карты',
            },
        ),
    ]
