# Generated by Django 5.1.6 on 2025-03-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcard',
            name='org_signature',
            field=models.JSONField(blank=True, null=True, verbose_name='Организационная подпись'),
        ),
    ]
