# Generated by Django 5.1.6 on 2025-03-25 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_remove_medicalcard_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('suffix', models.CharField(blank=True, max_length=16, null=True, verbose_name='Суффикс номера карты')),
                ('prefix', models.CharField(blank=True, max_length=16, null=True, verbose_name='Префикс номера карты')),
                ('begin_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Начальный номер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип мед.карты',
                'verbose_name_plural': 'Типы мед.карты',
            },
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='number',
            field=models.CharField(default=None, max_length=64, verbose_name='Номер карты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='card_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_card_types', to='registry.medicalcardtype', verbose_name='Тип карты'),
        ),
    ]
