# Generated by Django 5.1.6 on 2025-04-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('delivered', 'Доставлено'), ('unsent', 'Не доставлено'), ('planning', 'Планируется')], max_length=32, verbose_name='Статус'),
        ),
    ]
