# Generated by Django 5.1.6 on 2025-04-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planning', 'планирование'), ('confirmation', 'подтверждение'), ('cancellation', 'отмена')], max_length=20, verbose_name='Статус')),
                ('vizit_datetime', models.DateTimeField(verbose_name='Дата записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Запись на прием',
                'verbose_name_plural': 'Записи на прием',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('code', models.CharField(blank=True, max_length=32, null=True, verbose_name='Код')),
                ('synonym', models.TextField(blank=True, null=True, verbose_name='Синонимы')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Диагноз',
                'verbose_name_plural': 'Диагнозы',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Категории диагноза',
                'verbose_name_plural': 'Категории диагнозов',
            },
        ),
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_signed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Подписано ЭП')),
                ('signed_date', models.DateField(auto_now=True, null=True, verbose_name='Дата подписания')),
                ('org_signature', models.TextField(blank=True, null=True, verbose_name='Организационная подпись')),
                ('reception_document', models.TextField(blank=True, null=True, verbose_name='Документ приема')),
                ('reception_document_fields', models.JSONField(blank=True, null=True, verbose_name='Поля документа')),
                ('is_first_appointment', models.BooleanField(default=True, help_text='Флаг, означающий, что это первичный прием пациента', verbose_name='Флаг первого приема')),
                ('is_closed', models.BooleanField(default=False, help_text='Флаг, указывающий, что приём закрыт', verbose_name='Приём закрыт')),
                ('reason_for_inspection', models.TextField(blank=True, help_text='Основание направления (основание должны быть по документам)', null=True, verbose_name='Основание направления на обследование')),
                ('inspection_choice', models.CharField(choices=[('no_inspection', 'Не нуждается в обследовании'), ('additional', 'Нуждается в проведении доп обследования'), ('center', 'Нуждается в обследовании в центре'), ('ambulatory', 'Нуждается в амбулаторном обследовании'), ('stationary', 'Нуждается в стационарном обследовании'), ('sanatorium', 'Нуждается в санаторно-курортном лечении'), ('dispensary', 'Нуждается в диспансерном наблюдении'), ('preventive', 'Нуждается в лечебно-профилактических мероприятиях'), ('referral', 'Нуждается в направлении на медико-социальную экспертизу')], default='no_inspection', max_length=50, verbose_name='Тип обследования')),
                ('appointment_date', models.DateField(help_text='Укажите дату приема (YYYY-MM-DD)', verbose_name='Дата приема')),
                ('start_time', models.TimeField(help_text='Время начала приема', verbose_name='Время начала приема')),
                ('end_time', models.TimeField(help_text='Время окончания приема', verbose_name='Время окончания приема')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Приём к врачу',
                'verbose_name_plural': 'Приёмы к врачу',
            },
        ),
        migrations.CreateModel(
            name='HospitalStays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.TextField(blank=True, null=True, verbose_name='Документ смены')),
                ('document_fields', models.JSONField(blank=True, null=True, verbose_name='Поля документа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата госпитализации')),
                ('end_date', models.DateField(verbose_name='Дата выписки')),
                ('ward_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер палаты')),
            ],
            options={
                'verbose_name': 'Госпитализация',
                'verbose_name_plural': 'Госпитализации',
            },
        ),
        migrations.CreateModel(
            name='PatientCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.TextField(blank=True, null=True, verbose_name='Документ смены')),
                ('document_fields', models.JSONField(blank=True, null=True, verbose_name='Поля документа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание состояния пациента')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('status', models.CharField(choices=[('Critical', 'Критическое'), ('Worsening', 'Ухудшение'), ('Stable', 'Стабильное'), ('Improving', 'Улучшение'), ('Recovering', 'Выздоровление'), ('Post-operative', 'Послеоперационное'), ('Unstable', 'Неустойчивое'), ('No change', 'Без изменений')], max_length=64, verbose_name='Статус состояния пацента')),
            ],
            options={
                'verbose_name': 'Состояние пациента',
                'verbose_name_plural': 'Состояния пациентов',
            },
        ),
        migrations.CreateModel(
            name='ReceptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание шаблона')),
                ('html', models.TextField(blank=True, null=True, verbose_name='Шаблон')),
                ('fields', models.JSONField(blank=True, null=True, verbose_name='Поля приема')),
            ],
            options={
                'verbose_name': 'Шаблон приема',
                'verbose_name_plural': 'Шаблоны приемов',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.TextField(blank=True, null=True, verbose_name='Документ смены')),
                ('document_fields', models.JSONField(blank=True, null=True, verbose_name='Поля документа')),
                ('start_time', models.DateTimeField(verbose_name='Время начала смены')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания смены')),
            ],
            options={
                'verbose_name': 'Врачебная смена',
                'verbose_name_plural': 'Врачебные смены',
            },
        ),
        migrations.CreateModel(
            name='ShiftTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.TextField(blank=True, null=True, verbose_name='Документ смены')),
                ('document_fields', models.JSONField(blank=True, null=True, verbose_name='Поля документа')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Время передачи')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Передача врачебной смены',
                'verbose_name_plural': 'Передача врачебных смен',
            },
        ),
    ]
