# Generated by Django 5.1.6 on 2025-04-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_activity', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingappointment',
            name='status',
            field=models.CharField(choices=[('planning', 'планирование'), ('confirmation', 'подтверждение'), ('cancellation', 'отмена')], max_length=20, verbose_name='Статус'),
        ),
    ]
