# Generated by Django 5.1.6 on 2025-03-28 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_patient_passport_number_patient_passport_series'),
        ('medical_activity', '0004_doctorappointment_appointment_date_and_more'),
        ('staffing', '0005_specialization_employee_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('code', models.CharField(blank=True, max_length=32, null=True, verbose_name='Код')),
                ('synonym', models.TextField(blank=True, null=True, verbose_name='Синонимы')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Диагноз',
                'verbose_name_plural': 'Диагнозы',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Категории диагноза',
                'verbose_name_plural': 'Категории диагнозов',
            },
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='reception_document',
            field=models.TextField(blank=True, null=True, verbose_name='Документ приема'),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='reception_document_fields',
            field=models.JSONField(blank=True, null=True, verbose_name='Поля документа'),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medical_activity.diagnosis', verbose_name='Диагноз'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medical_activity.diagnosiscategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='ReceptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание шаблона')),
                ('html', models.TextField(blank=True, null=True, verbose_name='Шаблон')),
                ('fields', models.JSONField(blank=True, null=True, verbose_name='Поля приема')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staffing.specialization', verbose_name='Специализация шаблона')),
            ],
            options={
                'verbose_name': 'Шаблон приема',
                'verbose_name_plural': 'Шаблоны приемов',
            },
        ),
        migrations.CreateModel(
            name='HospitalStays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.TextField(blank=True, null=True, verbose_name='Документ смены')),
                ('document_fields', models.JSONField(blank=True, null=True, verbose_name='Поля документа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата госпитализации')),
                ('end_date', models.DateField(verbose_name='Дата выписки')),
                ('ward_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер палаты')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical_activity.doctorappointment', verbose_name='Прием')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.patient', verbose_name='Пациент')),
                ('document_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medical_activity.receptiontemplate', verbose_name='Шаблон документа')),
            ],
            options={
                'verbose_name': 'Госпитализация',
                'verbose_name_plural': 'Госпитализации',
            },
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='reception_template',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='medical_activity.receptiontemplate', verbose_name='Шаблон приема'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.TextField(blank=True, null=True, verbose_name='Документ смены')),
                ('document_fields', models.JSONField(blank=True, null=True, verbose_name='Поля документа')),
                ('start_time', models.DateTimeField(verbose_name='Время начала смены')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания смены')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staffing.employee', verbose_name='Врач')),
                ('document_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medical_activity.receptiontemplate', verbose_name='Шаблон документа')),
            ],
            options={
                'verbose_name': 'Врачебная смена',
                'verbose_name_plural': 'Врачебные смены',
            },
        ),
        migrations.CreateModel(
            name='PatientCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.TextField(blank=True, null=True, verbose_name='Документ смены')),
                ('document_fields', models.JSONField(blank=True, null=True, verbose_name='Поля документа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание состояния пациента')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('status', models.CharField(choices=[('Critical', 'Критическое'), ('Worsening', 'Ухудшение'), ('Stable', 'Стабильное'), ('Improving', 'Улучшение'), ('Recovering', 'Выздоровление'), ('Post-operative', 'Послеоперационное'), ('Unstable', 'Неустойчивое'), ('No change', 'Без изменений')], max_length=64, verbose_name='Статус состояния пацента')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.patient', verbose_name='Пациент')),
                ('document_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medical_activity.receptiontemplate', verbose_name='Шаблон документа')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical_activity.shift', verbose_name='Врачебная смена')),
            ],
            options={
                'verbose_name': 'Состояние пациента',
                'verbose_name_plural': 'Состояния пациентов',
            },
        ),
        migrations.CreateModel(
            name='ShiftTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.TextField(blank=True, null=True, verbose_name='Документ смены')),
                ('document_fields', models.JSONField(blank=True, null=True, verbose_name='Поля документа')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Время передачи')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('document_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medical_activity.receptiontemplate', verbose_name='Шаблон документа')),
                ('from_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifttransfer_from_set', to='medical_activity.shift', verbose_name='Какая смена передается')),
                ('to_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifttransfer_to_set', to='medical_activity.shift', verbose_name='Другая смена')),
            ],
            options={
                'verbose_name': 'Передача врачебной смены',
                'verbose_name_plural': 'Передача врачебных смен',
            },
        ),
    ]
