# Generated by Django 5.1.6 on 2025-04-01 17:51

import apps.abstract_models.person.validators
import apps.clients.validators.patients
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('inn', models.CharField(help_text='Введите 10 или 12 цифр ИНН', max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('bank_account', models.CharField(blank=True, max_length=128, null=True, verbose_name='Основной банковский счёт')),
                ('economic_activity_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид экономической деятельности')),
                ('ownership_form', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма собственности')),
                ('insurance_organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страховая организация')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, validators=[apps.abstract_models.person.validators.validate_last_name], verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, validators=[apps.abstract_models.person.validators.validate_first_name], verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True, validators=[apps.abstract_models.person.validators.validate_patronymic], verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('U', 'Не указан')], default='U', max_length=1, validators=[apps.abstract_models.person.validators.validate_gender], verbose_name='Пол')),
                ('date_of_birth', models.DateField(blank=True, null=True, validators=[apps.abstract_models.person.validators.validate_date_of_birth], verbose_name='Дата рождения')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('snils', models.CharField(blank=True, help_text='Укажите СНИЛС в формате 123-456-789 01 или 12345678901', max_length=14, null=True, validators=[apps.abstract_models.person.validators.validate_snils], verbose_name='СНИЛС')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, validators=[apps.abstract_models.person.validators.validate_inn], verbose_name='ИНН')),
                ('passport_series', models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='Серия паспорта должна состоять ровно из 4 цифр', regex='^\\d{4}$')], verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Номер паспорта должен состоять ровно из 6 цифр', regex='^\\d{6}$')], verbose_name='Номер паспорта')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', validators=[apps.abstract_models.person.validators.validate_photo_size], verbose_name='Фото')),
                ('registration_address', models.CharField(blank=True, max_length=255, null=True, validators=[apps.abstract_models.person.validators.validate_address], verbose_name='Адрес регистрации')),
                ('actual_address', models.CharField(blank=True, max_length=255, null=True, validators=[apps.abstract_models.person.validators.validate_address], verbose_name='Адрес фактического проживания')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[apps.abstract_models.person.validators.validate_phone], verbose_name='Номер телефона')),
                ('place_of_work', models.CharField(blank=True, max_length=255, null=True, validators=[apps.clients.validators.patients.validate_place_of_work], verbose_name='Место работы')),
                ('additional_place_of_work', models.CharField(blank=True, max_length=255, null=True, validators=[apps.clients.validators.patients.validate_additional_place_of_work], verbose_name='Дополнительное место работы')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, validators=[apps.clients.validators.patients.validate_profession], verbose_name='Профессия')),
                ('oms', models.CharField(blank=True, max_length=255, null=True, verbose_name='ОМС')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.contractor', verbose_name='Контрагент (работодатель клиента)')),
                ('legal_representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.patient', verbose_name='Законный представитель')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
    ]
