# Generated by Django 5.1.6 on 2025-03-21 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_contractor_uuid_remove_patient_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='passport_number',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Номер паспорта должен состоять ровно из 6 цифр', regex='^\\d{6}$')], verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='patient',
            name='passport_series',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='Серия паспорта должна состоять ровно из 4 цифр', regex='^\\d{4}$')], verbose_name='Серия паспорта'),
        ),
    ]
