# Generated by Django 5.1.6 on 2025-04-02 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('external_systems', '0001_initial'),
        ('staffing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='staffing.employee', verbose_name='Кем подписан'),
        ),
        migrations.AddIndex(
            model_name='laboratoryresearch',
            index=models.Index(fields=['lab_direction_guid'], name='external_sy_lab_dir_f5c9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoryresearch',
            index=models.Index(fields=['patient'], name='external_sy_patient_840b96_idx'),
        ),
    ]
