# Generated by Django 5.1.6 on 2025-03-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='position',
            name='uuid',
        ),
    ]
