# Generated by Django 5.1.6 on 2025-03-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Чат ID телеграмма для отправки уведомлений'),
        ),
    ]
