# Generated by Django 5.1.6 on 2025-03-21 08:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0003_remove_employee_uuid_remove_position_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Номер паспорта должен состоять ровно из 6 цифр', regex='^\\d{6}$')], verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_series',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='Серия паспорта должна состоять ровно из 4 цифр', regex='^\\d{4}$')], verbose_name='Серия паспорта'),
        ),
        migrations.CreateModel(
            name='ReceptionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_day', models.DateField(help_text='Укажите дату приёма (YYYY-MM-DD)', verbose_name='День приёма')),
                ('start_time', models.TimeField(help_text='Время начала рабочего периода', verbose_name='Время начала')),
                ('end_time', models.TimeField(help_text='Время окончания рабочего периода', verbose_name='Время окончания')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception_times', to='staffing.employee', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Время приёма',
                'verbose_name_plural': 'Время приёма',
                'ordering': ['doctor', 'reception_day', 'start_time'],
            },
        ),
    ]
