# Generated by Django 5.1.6 on 2025-03-28 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0004_employee_passport_number_employee_passport_series_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название специализации')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание специализации')),
            ],
            options={
                'verbose_name': 'Специализация врача',
                'verbose_name_plural': 'Специализации врачей',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffing.specialization', verbose_name='Специализация'),
        ),
    ]
