export type { Patient } from './model/model.ts'
export type { PaginatedPatientList } from './model/model.ts'
export type { PatientListQueryParams } from './model/model.ts'
export type { NewPatient } from './model/model.ts'
export { getAllPatients } from './api/getAllPatients.ts'